CREATE DATABASE IF NOT EXISTS allocat;
USE allocat;
CREATE TABLE roles (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(30) NOT NULL UNIQUE);
INSERT IGNORE INTO roles (name) VALUES ('ADMIN'), ('REQUESTER'), ('AUDITOR');
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, hashed_password VARCHAR(255) NOT NULL, role_id INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, is_active BOOLEAN DEFAULT TRUE, FOREIGN KEY (role_id) REFERENCES roles(id));
CREATE TABLE resources (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, category VARCHAR(80) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'DISPONIBLE', version INT NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reservations (id INT AUTO_INCREMENT PRIMARY KEY, resource_id INT NOT NULL, requester_id INT NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE', approved_by INT NULL, version INT NOT NULL DEFAULT 1, FOREIGN KEY (resource_id) REFERENCES resources(id), FOREIGN KEY (requester_id) REFERENCES users(id), FOREIGN KEY (approved_by) REFERENCES users(id));
CREATE TABLE audit_logs (id INT AUTO_INCREMENT PRIMARY KEY, action VARCHAR(30) NOT NULL, table_name VARCHAR(80) NOT NULL, record_id INT, user_id INT, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, details JSON, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE notifications (id INT AUTO_INCREMENT PRIMARY KEY, recipient_id INT NOT NULL, subject VARCHAR(200) NOT NULL, body TEXT NOT NULL, sent BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (recipient_id) REFERENCES users(id));
